/* ==========================================================================
   CONFIG / SOUND.JS  —  THE MUSIC AND THE MEOWS
   ==========================================================================

   Numbers and words only. See js/config/basics.js for how to change
   things without breaking them.
   ========================================================================== */

var CONFIG = CONFIG || {};   // join the shared settings (the first settings file to load creates it)

Object.assign(CONFIG, {

  /* ------------------------------------------------------------------
     SOUND
     ------------------------------------------------------------------
     Every sound here is generated by the browser from scratch — there are
     no music files. Turn the volumes down to 0 to silence them.
     ------------------------------------------------------------------ */

  AUDIO: {
    masterVolume: 0.85,
    musicVolume: 0.16,
    sfxVolume: 0.32,
    musicOn: true,

    // How long each note of the background music lasts, in seconds.
    // Bigger number = slower, sleepier music.
    noteSeconds: 0.46,

    // The cosy loop. Four bars, four notes each. Change the note names if
    // you fancy a different tune — 'C4' is middle C, 'C3' is an octave down.
    musicBars: [
      { bass: 'C3', notes: ['C4', 'E4', 'G4', 'E4'] },
      { bass: 'A2', notes: ['A3', 'C4', 'E4', 'C4'] },
      { bass: 'F2', notes: ['F3', 'A3', 'C4', 'A3'] },
      { bass: 'G2', notes: ['G3', 'B3', 'D4', 'B3'] }
    ],

    /* --- MEOWS IN THE MUSIC ------------------------------------------
       The cats sing along with the tune. A meow is dropped in on every
       'meowEveryNotes'th note of the music, pitched to match the melody.

         meowEveryNotes: 2  = a meow every other note (very meowy)
         meowEveryNotes: 4  = one meow per bar (the default)
         meowEveryNotes: 8  = one meow every two bars (calmer)
         meowsInMusic: false = no singing cats at all
       ------------------------------------------------------------------ */
    meowsInMusic: true,
    meowEveryNotes: 4,
    meowStartsOnNote: 2,
    musicMeowVolume: 0.34,
    musicMeowPitch: 2.1,       // how high the singing cats are. 2 = one octave up

    // Random background meows from around the village, in seconds.
    ambientMeowSeconds: 11,
    meowBasePitch: 560
  },

});
